### ISSUE TITLE
Calculating CC Payment on unused account

### ISSUE THREAD

**Issue by nickbart450** [nickbart450/ibudget_web#1]
Could not add transaction to credit card account with no existing payments.

```
2023-04-24 13:24:24,565: 
Recalculating upcoming credit card payment -- 811 modified
2023-04-24 13:24:24,611: Exception on /transact/submit_transaction [POST]
Traceback (most recent call last):
  File "/home/nick450/.virtualenvs/venv_budget/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nick450/.virtualenvs/venv_budget/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nick450/.virtualenvs/venv_budget/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nick450/.virtualenvs/venv_budget/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/nick450/ibudget_web/components/modify_transactions.py", line 38, in submit_transaction
    DATA.add_transaction(
  File "/home/nick450/ibudget_web/budget_data.py", line 348, in add_transaction
    self.update_credit_card_payment(transaction_id)
  File "/home/nick450/ibudget_web/budget_data.py", line 776, in update_credit_card_payment
    raise RuntimeError("cc payments returned empty")
```

**Comment by nickbart450** [comment]
Fixed in commit https://github.com/nickbart450/ibudget_web/commit/609038dc4f0910fa697c56a864e50ef02d203dd0
